export default class Map
{
    constructor(){}
}

const JSON_Structure_Template = { "compressionlevel":-1,
"editorsettings":
   {
    "export":
       {
        "format":"json",
        "target":"map2.json"
       }
   },
"height":60,
"infinite":false,
"layers":[{"data":[],
        "height":60,
        "id":1,
        "name":"Membrane + cell",
        "opacity":1,
        "type":"tilelayer",
        "visible":true,
        "width":80,
        "x":0,
        "y":0
       }],
"nextlayerid":2,
"nextobjectid":1,
"orientation":"orthogonal",
"renderorder":"right-down",
"tiledversion":"1.5.0",
"tileheight":30,
"tilesets":[
       {
        "columns":6,
        "firstgid":1,
        "image":"tileset.png",
        "imageheight":30,
        "imagewidth":180,
        "margin":0,
        "name":"tileset",
        "spacing":0,
        "tilecount":6,
        "tileheight":30,
        "tiles":[
               {
                "id":0,
                "properties":[
                       {
                        "name":"collide",
                        "type":"bool",
                        "value":true
                       }]
               }, 
               {
                "id":1,
                "properties":[
                       {
                        "name":"collide",
                        "type":"bool",
                        "value":true
                       }]
               }, 
               {
                "id":2,
                "properties":[
                       {
                        "name":"collide",
                        "type":"bool",
                        "value":true
                       }]
               }, 
               {
                "id":3,
                "properties":[
                       {
                        "name":"collide",
                        "type":"bool",
                        "value":true
                       }, 
                       {
                        "name":"heat",
                        "type":"bool",
                        "value":false
                       }]
               }, 
               {
                "id":4,
                "properties":[
                       {
                        "name":"collide",
                        "type":"bool",
                        "value":true
                       }, 
                       {
                        "name":"heat",
                        "type":"bool",
                        "value":true
                       }]
               }, 
               {
                "id":5,
                "properties":[
                       {
                        "name":"heat",
                        "type":"bool",
                        "value":true
                       }]
               }],
        "tilewidth":30
       }],
"tilewidth":30,
"type":"map",
"version":1.5,
"width":80
};

//https://en.wikipedia.org/wiki/Procedural_generation